### ISSUE TITLE
Getting error when trying to run flutter

### ISSUE THREAD

**Issue by sajedulsakib001** [mumumusuc/termux-flutter#15] opened 2023-12-14 21:18 UTC
Here is the error please help 🙏🙏![Screenshot_2023-12-15-03-16-39-192_com.termux.jpg](https://github.com/mumumusuc/termux-flutter/assets/48612479/c238e59b-066d-4f12-9a0c-5c76db5c5b79)

**Comment by mumumusuc** [comment] 2023-12-15 00:15
Duplicate of #13

I will mention it in README, thanks.

**Comment by sajedulsakib001** [comment] 2023-12-15 05:30
>   
> Duplicate of #13
> 
> I will mention it in README, thanks.

Can you please help with installing Android SDK? 🙏

**Comment by mumumusuc** [comment] 2023-12-15 06:14
README updated.

> > Duplicate of #13
> > I will mention it in README, thanks.
> 
> Can you please help with installing Android SDK? 🙏

[Manually Installing Build Tools in AndroidIDE: A Step-by-Step Guide](https://androidide.com/blogs/getting-started/2023/07/17/manually-installing-build-tools-in-androidide/)

**Closed** 2023-12-20 13:54 UTC
